import os, sys
os.environ['EMERGENT_LLM_KEY'] = 'sk-emergent-7562a399754063b92B'
from emergentintegrations.llm.openai.video_generation import OpenAIVideoGeneration

video_gen = OpenAIVideoGeneration(api_key=os.environ['EMERGENT_LLM_KEY'])
script = sys.argv[1]  # e.g. "12a"
out_dir = '/app/marketing/production'
os.makedirs(out_dir, exist_ok=True)

prompts = {
    "12a": "Cinematic shot in a bright supermarket. A toddler sitting in a shopping trolley seat excitedly grabs a colourful kids snack bar from the shelf. The parent takes it and holds up their smartphone to scan the barcode. The phone screen shows a dark near-black background health app with four bright green corner bracket guides framing the barcode on a live camera view. The scan completes and the screen shows a dark background with a large circular progress ring in red with the number 4 in bold red text inside and the text /10 in small gray below, with a blue pill badge reading Ultra-Processed underneath. The parent frowns and shakes their head. Warm supermarket lighting, shallow depth of field, professional advertisement, 4K cinematic.",
    "12b": "Cinematic shot in a bright supermarket. A cute toddler in a shopping trolley reaches out and grabs another colourful packaged kids snack from the shelf with both hands. The parent laughs, takes the snack and scans the barcode with their smartphone. The phone screen shows a dark black background with a large circular progress ring in orange-red with the number 3 in bold red text, /10 in gray below, and a blue badge reading Ultra-Processed. The parent shows the phone to the toddler and shakes their head. The toddler looks confused and tilts their head. Warm bright supermarket lighting, eye-level camera angle, professional advertisement, 4K cinematic.",
    "12c": "Cinematic shot in a supermarket. A parent picks up a simple natural fruit and oat kids bar from the shelf and scans it with their phone. The phone screen shows a dark black background with a large circular progress ring in bright green with the number 8 in bold green text, /10 in gray below, and a blue badge reading Minimally Processed. Below are dark gray cards with green checkmark icons. The parent smiles triumphantly and hands the bar to the toddler in the shopping trolley who grabs it happily and giggles. Warm lighting, shallow depth of field, professional advertisement ending, 4K cinematic.",
    "13a": "Cinematic shot of a modern office desk at lunchtime. A person unpacks a supermarket meal deal placing a plastic-wrapped sandwich on the desk. They pick up their smartphone and scan the sandwich barcode. The phone screen shows a dark near-black background app with a large circular progress ring in deep red with the number 2 in bold red text, /10 in gray below, and a blue pill badge reading Ultra-Processed. Dark gray cards below show red warning badges listing Emulsifiers and Preservatives. The persons face drops with disappointment. A colleague in the blurred background watches while eating an apple. Fluorescent office lighting, shallow depth of field on the phone, professional advertisement, 4K cinematic.",
    "13b": "Cinematic office desk shot at lunchtime. A person scans a bag of crisps with their smartphone. The phone screen shows a dark black background with a red circular progress ring showing the number 3 in red text, /10 in gray, blue badge Ultra-Processed. They push the crisps aside frustrated and scan a bottled orange drink. The phone shows another red ring with the number 2, /10, Ultra-Processed. They stare at the three meal deal items on the desk looking defeated. A colleague behind them eating a green apple smirks slightly. Natural office lighting, professional advertisement, 4K cinematic.",
    "13c": "Cinematic office shot. A person has replaced their meal deal items. They scan a fresh prepared salad bowl with their phone. The screen shows a dark black background with a bright green circular progress ring, the number 7 in green, /10 in gray, blue badge reading Minimally Processed, with green checkmark cards below. They nod approvingly. They scan a banana and the screen shows green ring with 9, /10, Minimally Processed. They smile confidently and take a bite of the salad. The colleague in the background gives an approving thumbs up. Warm office lighting, professional advertisement ending, 4K cinematic.",
    "14a": "Cinematic modern gym setting. A muscular personal trainer in athletic wear confidently hands a protein bar to their client, pointing at the nutrition label. The client takes it, pulls out their smartphone and scans the barcode. The phone screen shows a dark near-black background with a large circular progress ring in red with the number 3 in bold red text, /10 in gray, and a blue pill badge reading Ultra-Processed. Dark gray cards show red HIGH badges listing Artificial Sweeteners. The client turns the phone screen toward the trainer with a skeptical raised eyebrow. The trainers confident expression fades to surprise. Modern gym lighting with equipment visible, shallow depth of field, professional advertisement, 4K cinematic.",
    "14b": "Cinematic gym shot. A personal trainer defensively pulls another protein bar from their gym bag and hands it over. The client scans it with their phone. Dark black screen with red circular ring showing the number 4, /10 in gray, Ultra-Processed badge. The trainer grabs a protein shake bottle from the bench. Client scans that too. Red ring again showing 2, /10, Ultra-Processed. The trainer puts their hands up in defeat looking embarrassed while the client shakes their head with a knowing smile. Modern gym with natural window light, professional advertisement, 4K cinematic.",
    "14c": "Cinematic gym shot. The client reaches into their own gym bag and pulls out a natural nut and seed bar. They scan it with their phone. The screen shows a dark black background with a bright green circular progress ring with the number 8 in bold green text, /10 in gray, blue badge reading Minimally Processed, dark cards with green checkmarks listing Almonds, Seeds and Oats. The client hands the bar to the trainer with a proud confident smile. The trainer looks at the phone screen impressed and nods respectfully. Both laugh together. Modern gym lighting, professional advertisement ending, 4K cinematic.",
    "01a": "Cinematic shot of a modern kitchen. A woman opens her fridge door and the camera reveals shelves stacked with various packaged foods and bottles. She pulls out her smartphone and scans the first item, a bottle of sauce. The phone screen shows a dark near-black background with a large circular progress ring in red with the number 3 in bold red, /10 in gray, and a blue badge reading Ultra-Processed. She puts it back and grabs a packaged ready meal. Warm kitchen lighting, shallow depth of field, professional advertisement, 4K cinematic.",
    "01b": "Cinematic kitchen shot. A woman continues scanning items from her open fridge. She scans a yoghurt pot, the phone shows dark background with red ring, number 4, /10, Ultra-Processed badge. She scans a juice carton, red ring again, number 2, /10, Ultra-Processed. She scans fresh vegetables and the phone shows a bright green ring with number 9, /10, Minimally Processed. She looks relieved. Warm kitchen lighting, items lined up on counter, professional advertisement, 4K cinematic.",
    "01c": "Cinematic kitchen shot. A woman stands back looking at her fridge contents now sorted on the counter. Several items have imaginary red glows and a few have green glows. She looks surprised at how many are ultra-processed. She picks up her phone showing the dark black app with a green Scan a Product button. She looks determined to make changes. Warm golden kitchen lighting, shallow depth of field, professional advertisement ending, 4K cinematic.",
    "02a": "Cinematic gym locker room shot. A muscular man in a tank top opens his gym bag and pulls out several protein bars and supplement shakes, laying them on the bench proudly. He picks up his smartphone and scans the first protein bar barcode. The phone screen shows a dark near-black background with a large circular progress ring in red with the number 3 in bold red, /10 in gray, and a blue badge reading Ultra-Processed with red HIGH badges below. His proud smile drops. Modern gym locker room lighting, shallow depth of field, professional advertisement, 4K cinematic.",
    "02b": "Cinematic gym locker room shot. A muscular man desperately scans another protein bar from his collection. The phone shows dark background with red ring, number 2, /10, Ultra-Processed. He scans his pre-workout shake. Red ring, number 1, /10, Ultra-Processed. He scans his recovery drink. Red ring, number 3, /10, Ultra-Processed. He stares at all his supplements in disbelief, rubbing the back of his head. Modern gym lighting, professional advertisement, 4K cinematic.",
    "02c": "Cinematic gym locker room shot. The muscular man holds up one last bar, a simple natural nut and date bar. He scans it nervously. The phone screen shows a dark background with a bright green circular ring, number 8, /10, blue badge Minimally Processed, green checkmarks below. He pumps his fist in celebration and takes a big bite. He throws the other bars in the bin behind him. Modern gym lighting, professional advertisement ending, triumphant moment, 4K cinematic.",
    "03a": "Cinematic supermarket shot. An attractive young couple walk into the store together, the woman grabs a basket and the man picks up a jar of pasta sauce from the shelf. The woman pulls out her phone and scans the barcode playfully. The phone screen shows a dark near-black background with a red circular progress ring, number 3, /10, blue badge Ultra-Processed. She shows him the screen with a disapproving look. He puts it back sheepishly. Warm romantic supermarket lighting, shallow depth of field, professional advertisement, 4K cinematic.",
    "03b": "Cinematic supermarket shot. A young couple shop together. The man confidently grabs a ready-made stir fry sauce. The woman scans it, phone shows dark background red ring, number 2, /10, Ultra-Processed. She shakes her head. He tries a third option, a fancy looking marinade. She scans it. Red ring, number 4, /10, Ultra-Processed. They both laugh at how many are failing. Warm supermarket lighting, playful energy between them, professional advertisement, 4K cinematic.",
    "03c": "Cinematic supermarket shot. The young couple find fresh ingredients together. She scans fresh vegetables, phone shows green ring number 9, /10, Minimally Processed. He scans olive oil, green ring 8, /10. They smile at each other and load the basket. They walk away together down the aisle looking happy and confident. Warm golden supermarket lighting, romantic feel, shallow depth of field, professional advertisement ending, 4K cinematic.",
    "07a": "Cinematic morning kitchen shot. Warm sunrise light through a window. A person in pyjamas pours cereal into a bowl. They pick up their phone from the counter and scan the cereal box barcode. The phone screen shows a dark near-black background with a large red circular progress ring, number 3, /10 in gray, blue badge Ultra-Processed. They stare at the bowl of cereal with a look of betrayal. Beautiful warm morning light, cozy kitchen setting, shallow depth of field, professional advertisement, 4K cinematic.",
    "07b": "Cinematic morning kitchen shot. The same person in pyjamas now scans their toast spread jar. Phone shows dark background, red ring, number 2, /10, Ultra-Processed. They scan the orange juice carton. Red ring, number 4, /10, Ultra-Processed. They look at their entire breakfast spread on the counter and slowly push the plate away. All three items have failed. Morning sunlight, kitchen setting, professional advertisement, 4K cinematic.",
    "07c": "Cinematic morning kitchen shot. The person picks up a single banana and scans it with their phone almost sarcastically. The screen shows dark background with bright green ring, number 9, /10, Minimally Processed. They stare at the banana, then back at their ultra-processed breakfast, then back at the banana. They take a bite of the banana with a resigned nod and slight smile. Morning sunlight, cozy kitchen, humorous ending, professional advertisement, 4K cinematic.",
    "09a": "Cinematic bright and airy influencer-style kitchen shot. A young attractive woman speaks enthusiastically to camera like a wellness influencer, holding up a sleek bottled smoothie with a clean trendy label. She gestures at it proudly presenting it as her favourite daily health drink. The lighting is perfect Instagram-style with plants in the background. She is very animated and excited. Professional social media content style, 4K cinematic.",
    "09b": "Cinematic kitchen shot. A hand reaches in from off camera holding a smartphone and scans the barcode on the trendy smoothie bottle the influencer is holding. The phone screen shows a dark near-black background with a large circular progress ring in deep red with the number 2 in bold red, /10 in gray, and a blue badge reading Ultra-Processed. Red warning cards show Artificial Sweeteners, Added Sugars, Emulsifiers. The influencers excited expression freezes then drops to shock. Dramatic pause. Same bright airy kitchen, professional advertisement, 4K cinematic.",
    "09c": "Cinematic kitchen shot. The influencer awkwardly puts down the smoothie and steps back. A text overlay area at the bottom of frame. The person with the phone holds up a real orange and a banana and blends them in a blender. They scan the fresh smoothie, phone shows dark background, bright green ring, number 9, /10, Minimally Processed. They look at the camera confidently. Clean bright kitchen, professional advertisement ending, 4K cinematic."
}

prompt = prompts[script]
outfile = f"{out_dir}/{script}.mp4"
print(f"Generating clip {script}...")
try:
    video_bytes = video_gen.text_to_video(prompt=prompt, model="sora-2", size="1280x720", duration=8, max_wait_time=600)
    if video_bytes:
        video_gen.save_video(video_bytes, outfile)
        print(f"DONE: {outfile} ({len(video_bytes)} bytes)")
    else:
        print("FAILED: no bytes")
except Exception as e:
    print(f"FAILED: {e}")
