import os, sys
os.environ['EMERGENT_LLM_KEY'] = 'sk-emergent-7562a399754063b92B'
from emergentintegrations.llm.openai.video_generation import OpenAIVideoGeneration

video_gen = OpenAIVideoGeneration(api_key=os.environ['EMERGENT_LLM_KEY'])
script = sys.argv[1]  # e.g. "12a"
out_dir = '/app/marketing/production'
os.makedirs(out_dir, exist_ok=True)

prompts = {
    "12a": "Cinematic shot in a bright supermarket. A toddler sitting in a shopping trolley seat excitedly grabs a colourful kids snack bar from the shelf. The parent takes it and holds up their smartphone to scan the barcode. The phone screen shows a dark near-black background health app with four bright green corner bracket guides framing the barcode on a live camera view. The scan completes and the screen shows a dark background with a large circular progress ring in red with the number 4 in bold red text inside and the text /10 in small gray below, with a blue pill badge reading Ultra-Processed underneath. The parent frowns and shakes their head. Warm supermarket lighting, shallow depth of field, professional advertisement, 4K cinematic.",
    "12b": "Cinematic shot in a bright supermarket. A cute toddler in a shopping trolley reaches out and grabs another colourful packaged kids snack from the shelf with both hands. The parent laughs, takes the snack and scans the barcode with their smartphone. The phone screen shows a dark black background with a large circular progress ring in orange-red with the number 3 in bold red text, /10 in gray below, and a blue badge reading Ultra-Processed. The parent shows the phone to the toddler and shakes their head. The toddler looks confused and tilts their head. Warm bright supermarket lighting, eye-level camera angle, professional advertisement, 4K cinematic.",
    "12c": "Cinematic shot in a supermarket. A parent picks up a simple natural fruit and oat kids bar from the shelf and scans it with their phone. The phone screen shows a dark black background with a large circular progress ring in bright green with the number 8 in bold green text, /10 in gray below, and a blue badge reading Minimally Processed. Below are dark gray cards with green checkmark icons. The parent smiles triumphantly and hands the bar to the toddler in the shopping trolley who grabs it happily and giggles. Warm lighting, shallow depth of field, professional advertisement ending, 4K cinematic.",
    "13a": "Cinematic shot of a modern office desk at lunchtime. A person unpacks a supermarket meal deal placing a plastic-wrapped sandwich on the desk. They pick up their smartphone and scan the sandwich barcode. The phone screen shows a dark near-black background app with a large circular progress ring in deep red with the number 2 in bold red text, /10 in gray below, and a blue pill badge reading Ultra-Processed. Dark gray cards below show red warning badges listing Emulsifiers and Preservatives. The persons face drops with disappointment. A colleague in the blurred background watches while eating an apple. Fluorescent office lighting, shallow depth of field on the phone, professional advertisement, 4K cinematic.",
    "13b": "Cinematic office desk shot at lunchtime. A person scans a bag of crisps with their smartphone. The phone screen shows a dark black background with a red circular progress ring showing the number 3 in red text, /10 in gray, blue badge Ultra-Processed. They push the crisps aside frustrated and scan a bottled orange drink. The phone shows another red ring with the number 2, /10, Ultra-Processed. They stare at the three meal deal items on the desk looking defeated. A colleague behind them eating a green apple smirks slightly. Natural office lighting, professional advertisement, 4K cinematic.",
    "13c": "Cinematic office shot. A person has replaced their meal deal items. They scan a fresh prepared salad bowl with their phone. The screen shows a dark black background with a bright green circular progress ring, the number 7 in green, /10 in gray, blue badge reading Minimally Processed, with green checkmark cards below. They nod approvingly. They scan a banana and the screen shows green ring with 9, /10, Minimally Processed. They smile confidently and take a bite of the salad. The colleague in the background gives an approving thumbs up. Warm office lighting, professional advertisement ending, 4K cinematic.",
    "14a": "Cinematic modern gym setting. A muscular personal trainer in athletic wear confidently hands a protein bar to their client, pointing at the nutrition label. The client takes it, pulls out their smartphone and scans the barcode. The phone screen shows a dark near-black background with a large circular progress ring in red with the number 3 in bold red text, /10 in gray, and a blue pill badge reading Ultra-Processed. Dark gray cards show red HIGH badges listing Artificial Sweeteners. The client turns the phone screen toward the trainer with a skeptical raised eyebrow. The trainers confident expression fades to surprise. Modern gym lighting with equipment visible, shallow depth of field, professional advertisement, 4K cinematic.",
    "14b": "Cinematic gym shot. A personal trainer defensively pulls another protein bar from their gym bag and hands it over. The client scans it with their phone. Dark black screen with red circular ring showing the number 4, /10 in gray, Ultra-Processed badge. The trainer grabs a protein shake bottle from the bench. Client scans that too. Red ring again showing 2, /10, Ultra-Processed. The trainer puts their hands up in defeat looking embarrassed while the client shakes their head with a knowing smile. Modern gym with natural window light, professional advertisement, 4K cinematic.",
    "14c": "Cinematic gym shot. The client reaches into their own gym bag and pulls out a natural nut and seed bar. They scan it with their phone. The screen shows a dark black background with a bright green circular progress ring with the number 8 in bold green text, /10 in gray, blue badge reading Minimally Processed, dark cards with green checkmarks listing Almonds, Seeds and Oats. The client hands the bar to the trainer with a proud confident smile. The trainer looks at the phone screen impressed and nods respectfully. Both laugh together. Modern gym lighting, professional advertisement ending, 4K cinematic."
}

prompt = prompts[script]
outfile = f"{out_dir}/{script}.mp4"
print(f"Generating clip {script}...")
try:
    video_bytes = video_gen.text_to_video(prompt=prompt, model="sora-2", size="1280x720", duration=8, max_wait_time=600)
    if video_bytes:
        video_gen.save_video(video_bytes, outfile)
        print(f"DONE: {outfile} ({len(video_bytes)} bytes)")
    else:
        print("FAILED: no bytes")
except Exception as e:
    print(f"FAILED: {e}")
